/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutDayIdRouteImport } from './routes/workout.$dayId'
import { Route as LibraryExerciseIdRouteImport } from './routes/library.$exerciseId'
import { Route as PlanDayDayIdRouteImport } from './routes/plan.day.$dayId'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDayIdRoute = WorkoutDayIdRouteImport.update({
  id: '/workout/$dayId',
  path: '/workout/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryExerciseIdRoute = LibraryExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => LibraryRoute,
} as any)
const PlanDayDayIdRoute = PlanDayDayIdRouteImport.update({
  id: '/day/$dayId',
  path: '/day/$dayId',
  getParentRoute: () => PlanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/library/$exerciseId': typeof LibraryExerciseIdRoute
  '/workout/$dayId': typeof WorkoutDayIdRoute
  '/plan/day/$dayId': typeof PlanDayDayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/library/$exerciseId': typeof LibraryExerciseIdRoute
  '/workout/$dayId': typeof WorkoutDayIdRoute
  '/plan/day/$dayId': typeof PlanDayDayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/library/$exerciseId': typeof LibraryExerciseIdRoute
  '/workout/$dayId': typeof WorkoutDayIdRoute
  '/plan/day/$dayId': typeof PlanDayDayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/progress'
    | '/library/$exerciseId'
    | '/workout/$dayId'
    | '/plan/day/$dayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/progress'
    | '/library/$exerciseId'
    | '/workout/$dayId'
    | '/plan/day/$dayId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/progress'
    | '/library/$exerciseId'
    | '/workout/$dayId'
    | '/plan/day/$dayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  WorkoutDayIdRoute: typeof WorkoutDayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$dayId': {
      id: '/workout/$dayId'
      path: '/workout/$dayId'
      fullPath: '/workout/$dayId'
      preLoaderRoute: typeof WorkoutDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$exerciseId': {
      id: '/library/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/library/$exerciseId'
      preLoaderRoute: typeof LibraryExerciseIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/plan/day/$dayId': {
      id: '/plan/day/$dayId'
      path: '/day/$dayId'
      fullPath: '/plan/day/$dayId'
      preLoaderRoute: typeof PlanDayDayIdRouteImport
      parentRoute: typeof PlanRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryExerciseIdRoute: typeof LibraryExerciseIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryExerciseIdRoute: LibraryExerciseIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface PlanRouteChildren {
  PlanDayDayIdRoute: typeof PlanDayDayIdRoute
}

const PlanRouteChildren: PlanRouteChildren = {
  PlanDayDayIdRoute: PlanDayDayIdRoute,
}

const PlanRouteWithChildren = PlanRoute._addFileChildren(PlanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  WorkoutDayIdRoute: WorkoutDayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
